name: CI
run-name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install uv && sudo apt-get install just

      - name: Install app
        run: uv sync

      - name: Check linting and formatting
        run: just check

      - name: Run tests with Xvfb
        uses: GabrielBB/xvfb-action@v1
        with:
          run: just test
          options: -screen 0 1280x720x24
